Add `class` or any included in `HTMLAttributes`
astro-community/astro-embed pull request #18
Opened 2022-09-28 07:18 UTC by rikusen0335

Since `<Youtube />` ocmponent doesn't accepts class, but we have a situation that we need to style the element.
I am pleasure if you could add it by this PR or anything.

Please ask me anything you don't understand, my english is so bad

2022-09-28 08:54 UTC, delucis requested changes
Thanks @rikusen0335! Makes sense to extend the `Props` type like this 👍 

Changing `id` to `videoIdOrUrl` will be a breaking change (as you can see from the failing tests) and while sympathetic, I’d like to keep it as is for now.

2022-09-28 08:54 UTC, delucis commented on packages/astro-embed-youtube/YouTube.astro
> +	videoIdOrUrl: string;
I don’t think we can rename `id` at this point (maybe in the future) even though it does clash with the standard `id` attribute — bad choice on my part!

```suggestion
	id: string;
```

2022-09-28 08:54 UTC, delucis commented on packages/astro-embed-youtube/YouTube.astro
> +const { videoIdOrUrl, poster, ...attrs } = Astro.props as Props;
```suggestion
const { id, poster, ...attrs } = Astro.props as Props;
```

2022-09-28 08:54 UTC, delucis commented on packages/astro-embed-youtube/YouTube.astro
> +const videoid = extractID(videoIdOrUrl);
```suggestion
const videoid = extractID(id);
```

2022-09-28 14:05 UTC, rikusen0335 commented
Ohhhh yes, I forgot about backward compatibilities. We should stay keep id's not changed.

2022-09-28 14:06 UTC, rikusen0335 commented
I commited your change requests.
Let's see if the build work

2022-09-30 22:28 UTC, delucis approved these changes
I need to update some dependencies to make the tests run but I'm confident in this change nonetheless.

Thanks!

2022-09-30 22:28 UTC, merged